### ISSUE TITLE
setUser Error: Invalid request

### ISSUE THREAD

**Issue by ChiKaLiO** [bulentv/js_zklib#75]
I was just running the test script 😢 
```
Error: Invalid request�‼�l�⌂♦
    at Socket.handleOnData (....\zkteco\zklib\node_modules\zklib\zklib\zklib.js:95:45)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:326:22)
    at UDP.onMessage [as onmessage] (dgram.js:921:8)
```

**Comment by Rafiul585** [comment]
ZK.setUser(132, '', '8580', '132', (e) =>{
        ZK.disconnect();
        if (e) {
            console.log(e);
        } 
        else {
            console.log('Sucessfull!');  
        }
    })

I'm trying to set users on ZKteco device using this library, but it gives an error. Will you help me out from this troubleshoot? Is there anything wrong in my code?
